# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nb_id', models.IntegerField()),
                ('sf_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(default='Event', max_length=255)),
                ('creator_sf_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_sf_id', models.CharField(blank=True, max_length=100, null=True)),
                ('attended_before', models.BooleanField(default=False)),
                ('campaign_language', models.CharField(default='EN', max_length=2)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='LastSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
