# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmember',
            name='member_nb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
