# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_campaign_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sync_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
