# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160923_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='parent_id',
            field=models.CharField(default=b'701210000005hCN', max_length=255),
        ),
    ]
