# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160923_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='email_opt_in',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sync_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
