# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nb_hook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nationbuilder_tag', models.CharField(max_length=255)),
                ('salesforce_id', models.CharField(max_length=255)),
            ],
        ),
    ]
