# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nb_hook', '0002_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.TextField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False)),
            ],
        ),
    ]
