# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb_hook', '0004_contactsync_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsync',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
