# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb_hook', '0005_auto_20160831_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsync',
            name='type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
