# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb_hook', '0007_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
