# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nb_hook', '0008_auto_20160831_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
